version:  "3.9"
services:
  bancodedados:
    image: mariadb:latest
    container_name: bancodedados_composer
    environment:
        MYSQL_ROOT_PASSWORD: wordpress
        MYSQL_DATABASE: wordpress
        MYSQL_USER: wordpress
        MYSQL_PASSWORD: wordpress
    volumes: ["db_data_novo:/var/lib/mysql"]
  
  site:
    depends_on:
      - bancodedados
    image: wordpress-com-porto:1.5
    ports: ["9000:80"]
    volumes:
      - site_data:/var/www/html
    environment:
        WORDPRESS_DB_HOST: bancodedados:3306
        WORDPRESS_DB_USER: wordpress
        WORDPRESS_DB_PASSWORD: wordpress
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=bancodedados
volumes:
  db_data_novo:
  site_data: